### GET request to example server
GET http://localhost:8080

### Getting the card
GET http://localhost:8080/api/card/get

### Saving the data
POST http://localhost:8080/api/card/post
Content-Type: application/json

{
  "attack": 26000,
  "name": "Oblelisk",
  "level": 10
}

### Delete Card
DELETE http://localhost:8080/api/card/delete/Obelisk


### Update Card
PUT http://localhost:8080/api/card/update/Oblelisk
Content-Type: application/json

{
  "attack": 2400 ,
  "name": "Oblelisk",
  "level": 10
}

### Getting the Decks

GET http://localhost:8080/decks/get


### Creating a Deck
POST http://localhost:8080/decks/post
Content-Type: application/json

{
    "name": "Starter Deck"
}

### Deleting a deck
DELETE http://localhost:8080/decks/delete/Starter%20Deck

### Adding a card to the deck
POST http://localhost:8080/api/card/deck/addCard/Starter%20Deck
content-Type: application/json

{
  "name": "Summoned Skull",
  "attack": 2500,
  "level": 6
}